title: Dino's and Wino's
author: GingerBear
email: jonfaith88@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Top Dinosaurs and the wines they pair well with

# social links
twitter_username: TweeterTwittle
github_username:  GingerBear88

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
